"""Update delete schema for recupe and book

Revision ID: 07a97d728cc3
Revises: d9f853d3e66f
Create Date: 2026-07-03 12:15:57.502469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a97d728cc3'
down_revision = 'd9f853d3e66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes_books', schema=None) as batch_op:
        batch_op.drop_constraint('recipes_books_book_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipes_books_book_id_fkey', 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###
