""" Changed IngredientRecipe to Ingredient

Revision ID: 315a4a226bb0
Revises: 7caaa3be447b
Create Date: 2025-01-31 10:49:42.497116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '315a4a226bb0'
down_revision = '7caaa3be447b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes_ingredients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes_ingredients',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity_amount_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='recipes_ingredients_item_id_fkey'),
    sa.ForeignKeyConstraint(['quantity_amount_id'], ['quantity_amounts.id'], name='recipes_ingredients_quantity_amount_id_fkey'),
    sa.ForeignKeyConstraint(['quantity_unit_id'], ['quantity_units.id'], name='recipes_ingredients_quantity_unit_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='recipes_ingredients_recipe_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recipes_ingredients_pkey')
    )
    # ### end Alembic commands ###
