"""fixed attribute names in models

Revision ID: 366ebed06cb5
Revises: b800edad343d
Create Date: 2024-05-04 16:54:45.293270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366ebed06cb5'
down_revision = 'b800edad343d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('ingredients_unit_key', type_='unique')
        batch_op.create_unique_constraint(None, ['ingredient'])
        batch_op.drop_column('unit')

    with op.batch_alter_table('quantity_amounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('quantity_amounts_unit_key', type_='unique')
        batch_op.create_unique_constraint(None, ['amount'])
        batch_op.drop_column('unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quantity_amounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('quantity_amounts_unit_key', ['unit'])
        batch_op.drop_column('amount')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('ingredients_unit_key', ['unit'])
        batch_op.drop_column('ingredient')

    # ### end Alembic commands ###
