"""trying again

Revision ID: 3a2f85053c6b
Revises: d9ac962e0946
Create Date: 2024-04-27 16:18:35.933984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a2f85053c6b'
down_revision = 'd9ac962e0946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('u_s_e_r')
    op.drop_table('r_e_c_i_p_e_i_n_g_r_e_d_i_e_n_t')
    op.drop_table('r_e_c_i_p_e')
    op.drop_table('q_u_a_n_t_i_t_y_u_n_i_t')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('q_u_a_n_t_i_t_y_u_n_i_t',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='q_u_a_n_t_i_t_y_u_n_i_t_pkey'),
    sa.UniqueConstraint('unit', name='q_u_a_n_t_i_t_y_u_n_i_t_unit_key')
    )
    op.create_table('r_e_c_i_p_e',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('preparation', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='r_e_c_i_p_e_pkey')
    )
    op.create_table('r_e_c_i_p_e_i_n_g_r_e_d_i_e_n_t',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='r_e_c_i_p_e_i_n_g_r_e_d_i_e_n_t_pkey')
    )
    op.create_table('u_s_e_r',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='u_s_e_r_pkey'),
    sa.UniqueConstraint('email', name='u_s_e_r_email_key'),
    sa.UniqueConstraint('user_name', name='u_s_e_r_user_name_key')
    )
    # ### end Alembic commands ###
