"""create association table and relationship between Recipe & Instructions

Revision ID: 3db7e6a01a1c
Revises: 23665af94eb4
Create Date: 2024-10-14 11:34:20.130622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db7e6a01a1c'
down_revision = '23665af94eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes_instructions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instruction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'instructions', ['instruction_id'], ['id'])
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes_instructions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('instruction_id')
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###
