"""added mixin for association table

Revision ID: 465a0e11c6e3
Revises: 6dabc11a44dd
Create Date: 2024-07-08 15:40:13.404500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '465a0e11c6e3'
down_revision = '6dabc11a44dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_books')
    op.drop_table('user_books')
    op.drop_table('recipe_ingredients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity_amount_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name='recipe_ingredients_ingredient_id_fkey'),
    sa.ForeignKeyConstraint(['quantity_amount_id'], ['quantity_amounts.id'], name='recipe_ingredients_quantity_amount_id_fkey'),
    sa.ForeignKeyConstraint(['quantity_unit_id'], ['quantity_units.id'], name='recipe_ingredients_quantity_unit_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='recipe_ingredients_recipe_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recipe_ingredients_pkey')
    )
    op.create_table('user_books',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['recipe_books.id'], name='user_books_book_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_books_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_books_pkey')
    )
    op.create_table('recipe_books',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['recipe_books.id'], name='recipe_books_book_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='recipe_books_recipe_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recipe_books_pkey')
    )
    # ### end Alembic commands ###
