"""Quantity

Amount and QuantityUnit have nullable value

Revision ID: 5ac18c353d55
Revises: 1f590fadfa65
Create Date: 2025-03-26 11:01:40.680684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac18c353d55'
down_revision = '1f590fadfa65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quantity_amounts', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_constraint('quantity_amounts_value_key', type_='unique')

    with op.batch_alter_table('quantity_units', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_constraint('quantity_units_type_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quantity_units', schema=None) as batch_op:
        batch_op.create_unique_constraint('quantity_units_type_key', ['type'])
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('quantity_amounts', schema=None) as batch_op:
        batch_op.create_unique_constraint('quantity_amounts_value_key', ['value'])
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
