"""Create roles class and modify UserBook to accomodate roles column

Revision ID: 5c391a73fc35
Revises: d1067fac52e5
Create Date: 2025-09-03 12:07:34.347670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c391a73fc35'
down_revision = 'd1067fac52e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum(
            'owner', 'collaborator', 'viewer', name='book_role'), nullable=False))
        batch_op.drop_column('permission')
        batch_op.drop_column('id')

    op.create_index(
        "ux_one_owner_per_book",
        "users_books",
        ["book_id"],
        unique=True,
        postgresql_where=sa.text("role = 'owner'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.BIGINT(),
                            autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('permission', sa.VARCHAR(
            length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
