"""fixing naming of association tables

Revision ID: 6dabc11a44dd
Revises: b414120511f4
Create Date: 2024-07-08 15:32:13.102097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6dabc11a44dd'
down_revision = 'b414120511f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_book_recipes')
    with op.batch_alter_table('recipe_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'])
        batch_op.create_foreign_key(None, 'recipe_books', ['book_id'], ['id'])
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recipe_id')
        batch_op.drop_column('book_id')

    op.create_table('recipe_book_recipes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['recipe_books.id'], name='recipe_book_recipes_book_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='recipe_book_recipes_recipe_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recipe_book_recipes_pkey')
    )
    # ### end Alembic commands ###
