"""...

Revision ID: 7190fde8d4a9
Revises: 315a4a226bb0
Create Date: 2025-02-21 15:06:55.307743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7190fde8d4a9'
down_revision = '315a4a226bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('ingredients_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ingredients_recipe_id_fkey', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
