"""...

Revision ID: 7a29ed8d75e6
Revises: df0bb11a405c
Create Date: 2025-02-21 15:43:41.900939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a29ed8d75e6'
down_revision = 'df0bb11a405c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amounts_books', schema=None) as batch_op:
        batch_op.drop_constraint('amounts_books_amount_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('amounts_books_book_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quantity_amounts', ['amount_id'], ['id'])
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'])

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('ingredients_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'])

    with op.batch_alter_table('items_books', schema=None) as batch_op:
        batch_op.drop_constraint('items_books_book_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('items_books_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'])
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'])

    with op.batch_alter_table('recipes_books', schema=None) as batch_op:
        batch_op.drop_constraint('recipes_books_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'])

    with op.batch_alter_table('recipes_instructions', schema=None) as batch_op:
        batch_op.drop_constraint('recipes_instructions_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'])

    with op.batch_alter_table('units_books', schema=None) as batch_op:
        batch_op.drop_constraint('units_books_book_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('units_books_unit_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'])
        batch_op.create_foreign_key(None, 'quantity_units', ['unit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('units_books_unit_id_fkey', 'quantity_units', ['unit_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('units_books_book_id_fkey', 'books', ['book_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recipes_instructions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipes_instructions_recipe_id_fkey', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recipes_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipes_books_recipe_id_fkey', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('items_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('items_books_item_id_fkey', 'items', ['item_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('items_books_book_id_fkey', 'books', ['book_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ingredients_recipe_id_fkey', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('amounts_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('amounts_books_book_id_fkey', 'books', ['book_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('amounts_books_amount_id_fkey', 'quantity_amounts', ['amount_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
