"""fixed error:Mapper 'Mapper[Book(books)]' has no property 'quantity units'.

Revision ID: 7caaa3be447b
Revises: fbdf6cb71aa4
Create Date: 2025-01-24 16:24:56.118642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7caaa3be447b'
down_revision = 'fbdf6cb71aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('items_books_items_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('items_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('items_books_items_id_fkey', 'items', ['items_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
