"""added BookRecipe association table to hold relations between recipebooks and recipes

Revision ID: 96f9f72f7ba1
Revises: 5c20789e729a
Create Date: 2024-06-28 16:30:40.795284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96f9f72f7ba1'
down_revision = '5c20789e729a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recipes')
    with op.batch_alter_table('book_recipes', schema=None) as batch_op:
        batch_op.drop_constraint('book_recipes_book_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipe_books', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_recipes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('book_recipes_book_id_fkey', 'users', ['book_id'], ['id'])

    op.create_table('user_recipes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='user_recipes_recipe_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_recipes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_recipes_pkey')
    )
    # ### end Alembic commands ###
