"""WIP:DELETE statement on table 'ingredients' expected to delete 1 row(s); Only 0 were matched. 

Revision ID: a29e5914f5c2
Revises: a2217619a672
Create Date: 2025-02-24 11:01:01.793460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29e5914f5c2'
down_revision = 'a2217619a672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('ingredients_quantity_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('ingredients_quantity_amount_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('ingredients_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quantity_amounts', ['quantity_amount_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'quantity_units', ['quantity_unit_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ingredients_item_id_fkey', 'items', ['item_id'], ['id'])
        batch_op.create_foreign_key('ingredients_quantity_amount_id_fkey', 'quantity_amounts', ['quantity_amount_id'], ['id'])
        batch_op.create_foreign_key('ingredients_quantity_unit_id_fkey', 'quantity_units', ['quantity_unit_id'], ['id'])

    # ### end Alembic commands ###
