"""removed ingredients_recipe & quanity units


Revision ID: a96da9043849
Revises: 053d445340e6
Create Date: 2024-04-27 16:03:23.757594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a96da9043849'
down_revision = '053d445340e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quantityunits')
    op.drop_table('recipeingredients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipeingredients',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='recipeingredients_pkey')
    )
    op.create_table('quantityunits',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='quantityunits_pkey'),
    sa.UniqueConstraint('unit', name='quantityunits_unit_key')
    )
    # ### end Alembic commands ###
