"""changed quanity_amount_id & quantity_unit_id to nullable=True in Ingredient

Revision ID: b4aac6171922
Revises: 5ac18c353d55
Create Date: 2025-03-26 11:45:14.566358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4aac6171922'
down_revision = '5ac18c353d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.alter_column('quantity_amount_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quantity_unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.alter_column('quantity_unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity_amount_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
