"""Changed all occurences of Ingredient to Item along with underlying key name to 'name'

Revision ID: b6e2651ad689
Revises: 4a7e943933fc
Create Date: 2024-09-11 12:35:51.271578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6e2651ad689'
down_revision = '4a7e943933fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quantity_amounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('quantity_amounts_amount_key', type_='unique')
        batch_op.create_unique_constraint(None, ['value'])
        batch_op.drop_column('amount')

    with op.batch_alter_table('quantity_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('quantity_units_unit_key', type_='unique')
        batch_op.create_unique_constraint(None, ['type'])
        batch_op.drop_column('unit')

    with op.batch_alter_table('recipes_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('recipes_ingredients_ingredient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'items', ['ingredient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipes_ingredients_ingredient_id_fkey', 'ingredients', ['ingredient_id'], ['id'])

    with op.batch_alter_table('quantity_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('quantity_units_unit_key', ['unit'])
        batch_op.drop_column('type')

    with op.batch_alter_table('quantity_amounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('quantity_amounts_amount_key', ['amount'])
        batch_op.drop_column('value')

    op.create_table('ingredients',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ingredient', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ingredients_pkey'),
    sa.UniqueConstraint('ingredient', name='ingredients_ingredient_key')
    )
    # ### end Alembic commands ###
