"""Added relationships to tables

Revision ID: b800edad343d
Revises: 8812ca14522b
Create Date: 2024-05-03 16:25:38.395650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b800edad343d'
down_revision = '8812ca14522b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ingredient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quantity_unit_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quantity_amount_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ingredients', ['ingredient_id'], ['id'])
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'])
        batch_op.create_foreign_key(None, 'quantity_amounts', ['quantity_amount_id'], ['id'])
        batch_op.create_foreign_key(None, 'quantity_units', ['quantity_unit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quantity_amount_id')
        batch_op.drop_column('quantity_unit_id')
        batch_op.drop_column('ingredient_id')
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###
