"""Removed ownership from book - this wil be tracked in UserBook

Revision ID: be7a2f30ce57
Revises: 038eedb141f7
Create Date: 2026-02-03 15:50:08.026669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7a2f30ce57'
down_revision = '038eedb141f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('books_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('is_shared_book')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_type', sa.Enum('personal', 'collaborative', 'shared_inbox', name='book_type'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_books', schema=None) as batch_op:
        batch_op.drop_column('book_type')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_shared_book', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('books_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
