"""confiiguring models to handle deleting parents-child objects based on foreign key constraints.

Revision ID: c490c98d835b
Revises: 501196d6984c
Create Date: 2024-11-15 14:17:33.420033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c490c98d835b'
down_revision = '501196d6984c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes_books', schema=None) as batch_op:
        batch_op.drop_constraint('recipes_books_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recipes_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('recipes_ingredients_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recipes_instructions', schema=None) as batch_op:
        batch_op.drop_constraint('recipes_instructions_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes_instructions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipes_instructions_recipe_id_fkey', 'recipes', ['recipe_id'], ['id'])

    with op.batch_alter_table('recipes_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipes_ingredients_recipe_id_fkey', 'recipes', ['recipe_id'], ['id'])

    with op.batch_alter_table('recipes_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipes_books_recipe_id_fkey', 'recipes', ['recipe_id'], ['id'])

    # ### end Alembic commands ###
