"""Add permission column to UserBook

Revision ID: d1067fac52e5
Revises: ffba875f4650
Create Date: 2025-09-02 16:36:06.001866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1067fac52e5'
down_revision = 'ffba875f4650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_books', schema=None) as batch_op:
        batch_op.drop_column('permission')

    # ### end Alembic commands ###
