"""removing forked by column from Recipe

Revision ID: d9f853d3e66f
Revises: a16279493079
Create Date: 2026-03-24 10:22:25.913169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f853d3e66f'
down_revision = 'a16279493079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('recipes_forked_from_id_fkey', type_='foreignkey')
        batch_op.drop_column('forked_from_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forked_from_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('recipes_forked_from_id_fkey', 'recipes', ['forked_from_id'], ['id'])

    # ### end Alembic commands ###
