"""Baseline migration to match current state

Revision ID: e25e4f232faa
Revises: 465a0e11c6e3
Create Date: 2024-07-08 16:54:46.601826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25e4f232faa'
down_revision = '465a0e11c6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes_books', schema=None) as batch_op:
        batch_op.drop_constraint('recipes_books_book_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'])

    with op.batch_alter_table('users_books', schema=None) as batch_op:
        batch_op.drop_constraint('users_books_book_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_books_book_id_fkey', 'recipes_books', ['book_id'], ['id'])

    with op.batch_alter_table('recipes_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipes_books_book_id_fkey', 'recipes_books', ['book_id'], ['id'])

    # ### end Alembic commands ###
