"""WIP:DELETE statement on table 'ingredients' expected to delete 1 row(s); Only 0 were matched. 

Revision ID: ec8ade3b1daf
Revises: fc379f7e6068
Create Date: 2025-02-24 11:25:49.158566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8ade3b1daf'
down_revision = 'fc379f7e6068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('ingredients_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ingredients_recipe_id_fkey', 'recipes', ['recipe_id'], ['id'])

    # ### end Alembic commands ###
