"""changed book_id -> default_book_id to better convey meaning

Revision ID: fa7f383ef4c2
Revises: c490c98d835b
Create Date: 2025-01-13 09:58:10.914376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7f383ef4c2'
down_revision = 'c490c98d835b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_book_id', sa.BIGINT(), nullable=True))
        batch_op.drop_constraint('users_book_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'books', ['default_book_id'], ['id'])
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_book_id_fkey', 'books', ['book_id'], ['id'])
        batch_op.drop_column('default_book_id')

    # ### end Alembic commands ###
